---

#   iGjRxRljISqClgCoPZeWnklKSr6D-fR_jAgmaItFMZ0 

# Shall be replaced with proper/valid set.
# Self-signed certs are not supported.
metadata:
  layeringDefinition:
    abstract: false
    layer: site
  name: ingress-crt
  schema: metadata/Document/v1
  labels:
    name: ingress-crt-site
  storagePolicy: cleartext
schema: deckhand/Certificate/v1
data: |
  -----BEGIN CERTIFICATE-----
  iGjRxRljISqClgCoPZeWnklKSr6D-fR_jAgmaItFMZ0 
  -----END CERTIFICATE-----
...
---
metadata:
  layeringDefinition:
    abstract: false
    layer: site
  name: ingress-ca
  schema: metadata/Document/v1
  labels:
    name: ingress-ca-site
  storagePolicy: cleartext
schema: deckhand/CertificateAuthority/v1
data: |
  -----BEGIN CERTIFICATE-----
  iGjRxRljISqClgCoPZeWnklKSr6D-fR_jAgmaItFMZ0
  -----END CERTIFICATE-----
...
---
metadata:
  layeringDefinition:
    abstract: false
    layer: site
  name: ingress-key
  schema: metadata/Document/v1
  labels:
    name: ingress-key-site
  storagePolicy: cleartext
schema: deckhand/CertificateKey/v1
data: |
  -----BEGIN RSA PRIVATE KEY-----  
  iGjRxRljISqClgCoPZeWnklKSr6D-fR_jAgmaItFMZ0
  -----END RSA PRIVATE KEY-----
...
